let info = [
    {
        nome: "Stefano",
        descrizione: "Ha iniziato a praticare nel settembre 2010, appena iniziato il liceo. Dal primo allenamento (che fu una ripetizione di otto movimenti di quadrupedia, i 31-21-11, versione light dei  famosi 101) non ha mai smesso di pensare alla pratica e interpretarla intorno a sè. Ciò che lo colpì di più, lasciando un segno ancora vivo in lui, fu l’atto rivoluzionario ed “eroico” del mettere le mani per terra, sull’asfalto, al ciglio della strada. Ed è proprio questo concetto di rivolta, di innovazione e di reinterpretazione dello spazio, del corpo e del tempo, che cerca di condividere e trasmettere in ogni occasione possibile. Stefano si allena per una decina di anni con ADD Accademy Firenze, seguito prima da Giulio, Paolo e Taulant (quando era Parkour Firenze) e poi anche da Ax , Antonio e gli altri coach e assistenti di Firenze. Durante gli anni ha approfondito la pratica e il messaggio grazie agli eventi (Esprit Yamak) organizzati con i fondatori in tutta Italia e con periodici viaggi a Milano ad Évry dove tutto ha preso" + 
        "forma. Nel 2019 decide di aderire alla fondazione di RESPIRA Arte in Movimento con Andrea Santi e Pietro Galli mirando con il suo intento alla diffusione dell’Art Du Déplacement sul territorio."
    },
    {
        nome: "Andrea",
        descrizione: "Nato e cresciuto nella natura della Garfagnana e nutrito fin da piccolo all’amore per l’esplorazione, l’arte, il Movimento e la spiritualità, incontra l’Art Du Déplacement nel 2013 a Firenze dove sta approfondendo gli studi Umanistici. Ispirato dai caratteri psicologici e relazionali del gioco e delle esperienze sensoriali, riconosce da subito nell’Art Du Déplacement molti dei valori che cerca di nutrire e diffondere con la sua azione e il suo pensiero. Decide allora di approfondire questa disciplina ed elaborare un dialogo fra le sfere dell’arte che gli appartengono: educazione, teatro e Movimento per generare momenti di crescita al servizio dell’autenticità soggettiva e delle relazioni di comunità. Oggi quale cofondatore e presidente dell’ASD RESPIRA Arte in Movimento e dell’APS SPIRAMIRABILIS, fortemente ispirato dalla “pedagogia del corpo”, dal “movimento biologico”, dal “teatro dell’oppresso”  e dalla “nuova pedagogia”, continua la sua ricerca-zione intorno a un movimento esperienziale e liberatorio, quale strumento di scoperta e trasformazione delle sfere personali, sociali e culturali."
    },
    {
        nome: "Tiziano",
        descrizione: "Da sempre incuriosito e attratto dal movimento, dalla natura e dal suono. Le sue radici affondano nella musica, catturandolo fin dalla tenera età di 3 anni e accompagnandolo tutt'ora, nelle vesti di batterista. A 12 anni muove i suoi primi passi verso lo sport vero e proprio, praticando pallavolo per 3 anni e successivamente muay thai, per altri 4. Nel 2012 scopre per caso l'add, iniziando a praticare con Umberto Iannelli nel gruppo Parkour Prato, fino allo scioglimento avvenuto qualche anno più tardi. Nel frattempo continuerà a muoversi in solitaria fino al 2017, quando incontra altri 4 ragazzi, con cui condividere la stessa passione e tentare di riformare un nuovo gruppo di praticanti, allenandosi insieme ed esplorando nuove zone (sia di Prato, che nei dintorni). Nel frattempo passano altri 2 anni, nei quali cresce e si sviluppano sempre più forti il desiderio e la consapevolezza di voler intraprendere questa strada come percorso di vita. L'occasione arriva e si concretizza del tutto nel 2019/2020, dall'incontro con Andrea Santi e con la fondazione di Respira, dando finalmente nuova vita alla fiamma del movimento, con l'intento di promuovere e divulgare l'Art du Deplacement  sul territorio pratese e non solo, creando una realtà solida e unita."
    },
    {
        nome: "Miriam",
        descrizione: "Coadiuvante familiare in una Fattoria didattica e  capo Scout con un background da disegnatrice, si avvicina alla pratica nel 2015, grazie ad un numeroso gruppo di Prato. Finalmente aveva trovato una risposta al suo bisogno di ricercare la libertà nei pensieri e nel movimento. Purtroppo il gruppo ad un certo punto si sciolse, ma Miriam non smise del tutto di praticare. Fino al 2020, anno in cui si imbatté nell'associazione RESPIRA Arte in Movimento. Qui iniziò un nuovo  percorso pieno di sfide che la portò a lasciare la carriera artistica per intraprendere il viaggio per diventare istruttrice."
    }
]